apiVersion: cert-manager.io/v1
kind: {{ .Values.issuerKind }}
metadata:
  name: {{ .Values.issuerName }}
spec:
{{- if .Values.acme.enabled }}
  acme:
    server: {{ .Values.acme.server }}
    email: {{ .Values.acme.email }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: {{ .Values.azure.subscriptionID }}
          resourceGroupName: {{ .Values.azure.resourceGroup }}
          hostedZoneName: {{ .Values.azure.zoneName }}
          environment: AzurePublicCloud
          managedIdentity:
            clientID: {{ .Values.azure.managedidentity.clientID }}
{{- end}}
